on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t ghcr.io/iben12/dynu-updater .
      - name: Push image
        run: docker push ghcr.io/iben12/dynu-updater
